openapi: 3.0.4
info:
  title: Grammar Check
  description: Grammar Check is a simple tool for checking the grammar and spelling of a text. It returns the corrected text.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/grammarcheck:
    post:
      summary: Check Grammar and Spelling
      description: Grammar Check is a simple tool for checking the grammar and spelling of a text. It returns the corrected text.
      operationId: grammarcheck
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  modified: true
                  text: The pig snorted when I saw it on the barn gate. I Was a little mad because it woke up my puppy.
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text you want to check for grammatical and spelling errors
                  example: The the pig snorted when I saw it on the barn gate. I was a little mad becuase it woke up my pupppppy
              required:
              - text
              example:
                text: The the pig snorted when I saw it on the barn gate. I was a little mad becuase it woke up my pupppppy
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
